Add files via upload
kahvedigital/iyzico-woocommerce pull request #13
Opened 2018-03-05 13:50 UTC by kahvedigital

2018-03-06 14:05 UTC, heheok requested changes

2018-03-06 14:05 UTC, heheok commented on iyzico-payment-module/class-wc-gateway-iyzico-checkout-form.php
> +            $this->method_description = __('You can get your API ID and Secret key values from https://sandbox-merchant.iyzipay.com/settings.', 'iyzico-woocommerce-checkout-form');
sandbox?

2018-03-06 14:05 UTC, heheok commented on iyzico-payment-module/class-wc-gateway-iyzico-checkout-form.php
> +                            $installment_fee    = esc_sql($installment_fee);
sonucu neden escape ettik? Ayrıca değerin float olması gerektiği için escape etmeye gerek yok. floatval() fonksiyonu zaten string'i float a çevirir.

2018-03-06 14:05 UTC, heheok commented on iyzico-payment-module/class-wc-gateway-iyzico-checkout-form.php
> +                            update_post_meta($order_id, 'iyzi_installment_fee', esc_sql($installment_fee));
daha önce escape ettiğimiz değeri tekrar escape etmemiz performans açısından hayırlı olmaz.

2018-03-09 13:50 UTC, kahvedigital commented
update.

2018-03-14 08:01 UTC, heheok approved these changes

2018-03-14 08:01 UTC, merged